config/routes.rb
Ecommerce::Application.routes.draw do
  root :to => 'products#index'
  resources :products do
    collection do
      get "filter/:tag_id", :action => :filter, :as => :filter
      get "search"
    end
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  image       :string(255)
#  cost        :decimal(, )
#  lat         :float
#  long        :float
#  address     :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base
  attr_accessible :name, :description, :image, :cost, :address, :remote_image_url, :tags

  before_save :get_coords
  belongs_to :user
  has_and_belongs_to_many :tags
  mount_uploader :image, PicUploader

  private
  def get_coords
    result = Geocoder.search(self.address).first
    if result.present?
      self.lat = result.latitude
      self.long = result.longitude
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password, :password_confirmation, :is_admin, :balance
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate

  private
  def authenticate
    @auth = (session[:user_id].present?) ? User.find(session[:user_id]) : nil
  end

  def ensure_logged_in
    redirect_to(root_path) if @auth.nil?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(:name)
  end

  def new
    @product = Product.new
  end

  def create
    binding.pry
    product = Product.create(params[:product])
    tags = params[:tags].split(", ")
    product.save
    tags.each do |tag|
      if Tag.exists?(:name => tag)
        product.tags << Tag.where(:name => tag).first
      else
        product.tags << Tag.create(:name => tag)
      end
    end
    @products = Product.order(:name)
  end

  def filter
    tag = Tag.find(params[:tag_id])
    @products = tag.products
  end

  def search
    text = params[:text]
    @products = Product.where("name @@ :q or description @@ :q or image @@ :q or address @@ :q", :q => text)
    tags = Tag.where('name @@ :q', :q => text)
    tags = tags.map{|x| x.products}.flatten
    @products += tags
    @products.uniq!
    render :filter
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.where( email: params[:email] ).first
    if user.present? && user.authenticate( params[:password] )
      session[:user_id] = user.id
      @auth = user
      Notifications.login_message(@auth).deliver
      redirect_to(root_path)
    else
      session[:user_id] = nil
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    @auth = nil
    redirect_to(root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h3= link_to 'Nozama', '#'
  - if @auth.nil?
    %section.top-bar-section
      %ul.right
        %li= link_to("LOGIN", login_path)
        %li= link_to("REGISTER", '#', :method => 'delete')
  -else
    %section.top-bar-section
      %ul.right
        %li= link_to("#{@auth.email}", '#')
        %li= link_to("LOGOUT", login_path, :method => 'delete')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE']}&sensor=false" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => 'layouts/nav' %>
<%= yield %>

</body>
</html>

app/views/notifications/login_message.text.erb
Hey <%= @user.email %>,
You just logged in to E-Commerce. Enjoy your time on the site.

Sincerely,
E-Commerce Staff

app/views/products/_form.html.haml
=form_for @product, :html => {:multipart => true}, :remote => true do |f|
  =f.label :name
  =f.text_field :name
  =f.label :cost
  =f.number_field :cost
  = label_tag :tags
  = text_field_tag :tags
  =f.label :description
  =f.text_area :description
  =f.label :address
  =f.text_field :address
  =f.label :image
  =f.file_field :image
  =f.text_field :remote_image_url
  =f.submit nil, :class => "button radius success"
  =link_to("Cancel", "#", :"data-clear-photo-form" => true, :class => "button radius alert")

app/views/products/_products.html.haml
%table
  %tr
    %th Photo
    %th Name
    %th Price
    %th Desc
    %th Tags
    -@products.each do |product|
      %tr
        %td= image_tag(product.image.thumb.url)
        %td= product.name
        %td= number_to_currency(product.cost)
        %td= product.description
        %td
          -product.tags.each do |tag|
            %span= link_to("#{tag.name} - #{tag.products.length}", filter_products_path(tag.id), :remote => true, :class => "button radius tiny")

app/views/products/create.js.erb
$("#product_list").empty().append("<%=j render :partial => 'products'%>");
$("#product_form").empty();

app/views/products/filter.js.erb
$("#product_list").empty().append("<%=j render :partial => 'products'%>");

app/views/products/index.html.haml
.row
  .small-12.columns
    %h1 Nozama

-if @auth.present? && (@auth.is_admin == true)
  .row
    .small-8.small-centered.columns
      = link_to("Add Product", new_product_path, :remote => true, :class => "button radius alert")
      #product_form
.row
  .small-8.small-centered.columns
    #search_holder
      = text_field_tag :search, nil, :autofocus => true
    #product_list
      = render :partial => "products"

.row
  .small-8.small-centered.columns
    #map
      #map_canvas
        %script
          display_map(38.891033,-94.833984, 3)
          ="add_marker(#{@products.first.lat},#{@products.first.long}, 'test')"
          - @products.each do |product|
            = "add_marker(#{product.lat}, #{product.long}, '#{product.name}')"

app/views/products/new.js.erb
$("#product_form").empty().append("<%=j render :partial => 'form' %>");

app/views/session/new.html.haml
.row
  .large-4.offset-4.columns
    %h4 Login to Nozama
    = form_tag '/login' do
      = text_field_tag :email, nil,  :placeholder => 'Email'
      = password_field_tag :password, nil, :placeholder => "Password"

      = submit_tag('Login', :class=>'button radius small')